In [1]:
!pip install numpy

In [2]:
import numpy as np

In [3]:
a = np.array([1,2,3,"a"])

In [4]:
a

array(['1', '2', '3', 'a'], dtype='<U21')

In [5]:
a=np.array(2)
b=np.array([1,2,3])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6],[7,8,9]]])

In [6]:
print('a dimension:',a.ndim)
print('b dimension:',b.ndim)
print('c dimension:',c.ndim)
print('d dimension:',d.ndim)

a dimension: 0
b dimension: 1
c dimension: 2
d dimension: 3


In [7]:
print(a)
print("shape of a:",a.shape)
print(b)
print("shape of b:",b.shape)
print(c)
print("shape of c:",c.shape)
print(d)
print("shape of d:",d.shape)

2
shape of a: ()
[1 2 3]
shape of b: (3,)
[[1 2 3]
 [4 5 6]]
shape of c: (2, 3)
[[[1 2 3]
  [4 5 6]
  [7 8 9]]]
shape of d: (1, 3, 3)


In [8]:
print(a.dtype)
print(d.dtype)

int64
int64


In [9]:
print(type(a))
print(type(c))

<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [10]:
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [11]:
np.eye(3,)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [12]:
np.eye(3,dtype= int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [13]:
np.zeros((3,3),dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [14]:
np.ones((2,2),dtype=int)

array([[1, 1],
       [1, 1]])

In [15]:
np.full((5,5),8,dtype=int)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [16]:
x=[1,2,3,4,5,6,7,8]
np.diag(x)

array([[1, 0, 0, 0, 0, 0, 0, 0],
       [0, 2, 0, 0, 0, 0, 0, 0],
       [0, 0, 3, 0, 0, 0, 0, 0],
       [0, 0, 0, 4, 0, 0, 0, 0],
       [0, 0, 0, 0, 5, 0, 0, 0],
       [0, 0, 0, 0, 0, 6, 0, 0],
       [0, 0, 0, 0, 0, 0, 7, 0],
       [0, 0, 0, 0, 0, 0, 0, 8]])

In [17]:
x=np.arange(1,6)
print(x)
print(x.ndim)
print(x.shape)

[1 2 3 4 5]
1
(5,)


In [18]:
x=np.reshape(x,(5,1))
print(x)
print(x.ndim)
print(x.shape)

[[1]
 [2]
 [3]
 [4]
 [5]]
2
(5, 1)


In [19]:
w=x.ravel()
print(w)
print(w.ndim)
print(w.shape)

[1 2 3 4 5]
1
(5,)


In [20]:
x.flatten()

array([1, 2, 3, 4, 5])

In [21]:

a = np.arange(2,17,2)

In [22]:
a

array([ 2,  4,  6,  8, 10, 12, 14, 16])

In [23]:
#indexing
print(a[2])

6


In [24]:

print(a[0:7:2])

[ 2  6 10 14]


In [25]:
a=np.array([[1,2,3],[4,5,6],[7,8,9]])


In [26]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [27]:
print(a[1,1])

5


In [28]:
a=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
a

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [29]:
print(a[0][1][1])

5


In [32]:
#slicing
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[2:6])

[3 4 5 6]


Array Slicing


In [44]:
arr=np.arange(1,11)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10]


In [45]:
arr[1:6]

array([2, 3, 4, 5, 6])

In [46]:
arr[5:]

array([ 6,  7,  8,  9, 10])

In [70]:
a
a=([[1,2,3],
   [4,5,6],
   [7,8,9]])

In [73]:
a = np.array(a)
print(a[0:2,0:2])

[[1 2]
 [4 5]]


In [74]:
print(a[0:2,1:3])

[[2 3]
 [5 6]]


In [75]:
print(a[1:3,1:3])

[[5 6]
 [8 9]]


In [113]:
#3D Array
a
a = np.array([
    [[1, 2, 3], [4, 5, 6]],
    [[7, 8, 9], [10, 11, 12]]
])

In [116]:
print(a[0:2, 0:2, 1:2])

[[[ 2]
  [ 5]]

 [[ 8]
  [11]]]


In [76]:
x1 = np.arange(10)
x1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [79]:
x2=x1

In [80]:
print(x1)
print(x2)

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [81]:
print(id(x1))
print(id(x2))

135493203458928
135493203458928


In [82]:
print(np.shares_memory(x1,x2))
print(id(x1))
print(id(x2))


True
135493203458928
135493203458928


In [85]:
x3 =x1.view()

In [86]:
np.shares_memory(x1,x3)

True

In [87]:
x3[0]=100

In [88]:
print(x1)
print(x3)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8   9]


In [89]:
x4=np.copy(x1)

In [90]:
x4[-1]=900

In [91]:
print(x1)
print(x4)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


In [92]:
print(id(x1))
print(id(x4))

135493203458928
135493200723472


Condition Operation

In [ ]:
a
a=([[1,2,3],
   [4,5,6],
   [7,8,9]])

In [93]:
a>3

array([[False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

In [94]:
#get a list with all elements of array 'a' greater than 3
a[a>3]

array([4, 5, 6, 7, 8, 9])

In [97]:
#get a list with all elements of array 'a' greater than 3 but less than or equal to 7
a[(a>3)& (a<=7)]

array([4, 5, 6, 7])

In [98]:
x1==x4

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
       False])

In [100]:
print(a.transpose())

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [101]:
print(x1)
print(x4)
np.hstack((x1,x4))

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([100,   1,   2,   3,   4,   5,   6,   7,   8,   9, 100,   1,   2,
         3,   4,   5,   6,   7,   8, 900])

In [103]:
#inserting
print(x1)
print(x4)
np.insert(x1,3,9999)

[100   1   2   3   4   5   6   7   8   9]
[100   1   2   3   4   5   6   7   8 900]


array([ 100,    1,    2, 9999,    3,    4,    5,    6,    7,    8,    9])

In [104]:
print(x1)
np.delete(x1,3)

[100   1   2   3   4   5   6   7   8   9]


array([100,   1,   2,   4,   5,   6,   7,   8,   9])

In [105]:
#mathematical operations
arr = np.array([0,30,90])

print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[ 0.         -0.98803162  0.89399666]
[ 1.          0.15425145 -0.44807362]
[ 0.         -6.4053312  -1.99520041]


In [106]:
arr = np.array([1,2,3])

print(np.exp(arr))

[ 2.71828183  7.3890561  20.08553692]


In [107]:
arr = np.array([[1,2,3],[4,5,6]])

print(np.sum(arr))
print(np.sum(arr,axis=0))

21
[5 7 9]


In [109]:
arr = np.array([5,2,10,6])

print(np.max(arr))
print(np.min(arr))
print(np.sort(arr))
print(np.sort(arr)[::-1])  # Sort in descending order

10
2
[ 2  5  6 10]
[10  6  5  2]


In [110]:
arr = np.array([1,2,3,4,5])

print(np.where(arr==3))

(array([2]),)


In [111]:
# covert to list/set:
arr = np.array([1,2,3])

print(dir(list))
print(set(arr))
print(dir(dict))

['__add__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__iadd__', '__imul__', '__init__', '__init_subclass__', '__iter__', '__le__', '__len__', '__lt__', '__mul__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__reversed__', '__rmul__', '__setattr__', '__setitem__', '__sizeof__', '__str__', '__subclasshook__', 'append', 'clear', 'copy', 'count', 'extend', 'index', 'insert', 'pop', 'remove', 'reverse', 'sort']
{np.int64(1), np.int64(2), np.int64(3)}
['__class__', '__class_getitem__', '__contains__', '__delattr__', '__delitem__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getitem__', '__getstate__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__ior__', '__iter__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__reduce__', '__reduce_ex__', '

In [112]:
#keywords:
arr = np.array([1,2,3], dtype=float)
print(arr)
print(len(arr))

[1. 2. 3.]
3
